export const SIGNUP_BY_EMAIL_STARTED = 'SIGNUP_BY_EMAIL_STARTED';
export const SIGNUP_BY_EMAIL_FAIL = 'SIGNUP_BY_EMAIL_FAIL';
export const SIGNUP_BY_EMAIL_SUCCESS = 'SIGNUP_BY_EMAIL_SUCCESS';

export const LOGIN_BY_EMAIL_STARTED = 'LOGIN_BY_EMAIL_STARTED';
export const LOGIN_BY_EMAIL_SUCCESS = 'LOGIN_BY_EMAIL_SUCCESS';
export const LOGIN_BY_EMAIL_FAIL = 'LOGIN_BY_EMAIL_FAIL';