export const SIGNUP_BY_EMAIL_STARTED = 'SIGNUP_BY_EMAIL_STARTED';
export const SIGNUP_BY_EMAIL_FAIL = 'SIGNUP_BY_EMAIL_FAIL';
export const SIGNUP_BY_EMAIL_SUCCESS = 'SIGNUP_BY_EMAIL_SUCCESS';

export const LOGIN_BY_EMAIL_STARTED = 'LOGIN_BY_EMAIL_STARTED';
export const LOGIN_BY_EMAIL_SUCCESS = 'LOGIN_BY_EMAIL_SUCCESS';
export const LOGIN_BY_EMAIL_FAIL = 'LOGIN_BY_EMAIL_FAIL';

export const REMOVE_ERROS_ON_TAB_CHANGE = 'REMOVE_ERROS_ON_TAB_CHANGE';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_FAIL = 'USER_FAIL';

export const LOG_OUT = 'LOG_OUT';